import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from '../styles/Home.module.css'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Emergency Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header></Header>
        
        <h1 className={styles.title}>
          Welcome to Dire Dashboard
        </h1>

        <div className={styles.searchContainer}>
          <div className={styles.searchBarContainer}>
            <input className={styles.searchBar} type="text" placeholder="Search for buildings" />
            <img
              src="/img/search.png"
              className={styles.searchIcon}
            />
          </div>
          <a href="/results" className={styles.searchButton}>
            <h2>Search</h2>
          </a>
          <a href="/results" className={styles.browseButton}>
            <h2>Browse All Buildings</h2>
          </a>
        </div>

        
      </main>
    </div>
  )
}
